version: '3'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=backend_as_service2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
